spring:
  profiles:
    active: dev
  application:
    name: orm-mp-demo
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  servlet:
    context-path: /orm-mp-demo

management:
  endpoints:
    web:
      exposure:
        include: "*"