server:
  port: 8081

spring:
  boot:
    admin:
      client:
        instance:
          service-base-url: http://localhost:9000/admin
        url: http://localhost:9000/admin
  datasource:
    username: root
    password: Abcd1234
    url: jdbc:mysql://localhost:3306/awesome-java?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    # 开启sql查询打印
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 关闭打印
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

database-backup:
  ip: 10.18.140.200
  port: 3306
  username: root
  password: Abcd1234
  database-name: awesome-java
  save-path: /Users/yilan/backup
  filename: awesome-java.sql
