server:
  port: 8082

spring:
  boot:
    admin:
      client:
        url: http://localhost:9000/admin
  redis:
    host: localhost
    port: 6379
    # 如果设置了密码，则填写密码
    password:
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10000ms
    # Redis数据库索引（默认为0）
    database: 0
    # redis客户端使用Lettuce，也可使用jedis但不推荐
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0

#  cache:
#    # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
#    type: redis

logging:
  level:
    root: warn
    com.yilan.awesome: debug

