server:
  port: 8080

spring:
  application:
    name: management-service
  cloud:
    nacos:
      discovery:
        # 配置Nacos地址
        server-addr: localhost:8848
  datasource:
    username: root
    password: Abcd1234
    url: jdbc:mysql://localhost:3306/awesome-java?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver


# 设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  # 指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

#dubbo:
##  scan:
##    # 指定Dubbo服务实现类的扫描基准包
##    base-packages: com.yilan.awesome
##  # Dubbo服务暴露的协议配置，其中子属性name为协议名称，port为协议端口（-1 表示自增端口，从 20880 开始）
#  protocol:
#    name: dubbo
#    port: -1
#  registry:
#    address: nacos://localhost:8848
#  cloud:
#    subscribed-services: user-service

