server:
  port: 8080

spring:
  boot:
    admin:
      client:
        url: http://localhost:9000/admin
  datasource:
    username: root
    password: Abcd1234
    url: jdbc:mysql://localhost:3306/awesome-java?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
