spring:
  profiles:
    active: dev
  application:
    name: springmvc-demo
  jackson:
    time-zone: GMT+8



server:
  servlet:
    context-path: /springmvc-demo


management:
  endpoints:
    web:
      exposure:
        include: "*"
# spring-doc-openapi项目配置
#spring-doc:
#  swagger-ui:
#    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: alpha
#  api-docs:
#    path: /v3/api-docs
#  group-configs:
#    - group: '默认分组'
#      paths-to-match: '/**'
#      packages-to-scan: com.example
#
## knife4j的增强配置，不需要增强可以不配
#knife4j:
#  enable: true
#  setting:
#    enable-footer: false