spring:
  profiles:
    active: dev
  application:
    name: springmvc-demo
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


server:
  servlet:
    context-path: /springmvc-demo


management:
  endpoints:
    web:
      exposure:
        include: "*"