spring:
  cloud:
    gateway:
      routes:
        - id: admin_route
          uri: lb://admin-service
          predicates:
            - Path=/api/
          filters:
            - RewritePath= /api/(?<segment>.*),/$\{segment}