spring:
  profiles:
    active: dev
  application:
    name: logback
  jackson:
    time-zone: GMT+8



server:
  servlet:
    context-path: /logback


management:
  endpoints:
    web:
      exposure:
        include: "*"
